export type TileTypePrefix = 'climate' | 'mobility' | 'energy' | 'building'

export type ClimateTypes =
  | 'weather'
  | 'co2'
  | 'indices'
  | 'development'
  | 'garbage'
  | 'data'
  | 'lightning'
  | 'rainfall'
  | 'uv'
export type MobilityTypes =
  | 'bicycle'
  | 'stadtradeln'
  | 'bus'
  | 'modalSplit'
  | 'awm'
export type BuildingsTypes =
  | 'ecoProfit'
  | 'energyConsumption'
  | 'trafficload'
  | 'building'
  | 'masterplan'
  | 'passengers'
export type EnergyTypes =
  | 'PV'
  | 'wind'
  | 'energietraeger'
  | 'lanterns'
  | 'pvanlagen'
